# Spring DATASOURCE 
# application.properties

spring.datasource.url=jdbc:postgresql://localhost:5432/pratice?currentSchema=greythr
spring.datasource.username=postgres
spring.datasource.password=admin@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
